from typing import Protocol


class IUBaseRepoPort(Protocol):
    def create(self, data): ...
    def find(self, **kwargs): ...
    def find_all(self, **kwargs): ...
    def update(self, id, data): ...
    def delete(self, id): ...
