from typing import Protocol

class IUBaseRepoPort(Protocol):
    def create(self, data): ...
    def find(self, id): ...
    def find_all(
        self, 
        page: int, limit: int, 
        name: str = None, email: str = None
        ): ...
    def update(self, id, data): ...
    def delete(self, id): ...