from typing import Protocol

class IUBaseRepoPort(Protocol):
    def create(self, data): ...
    def find(self, data): ...
    def find_all(self, data): ...
    def update(self, data): ...
    def delete(self, data): ...